### ISSUE TITLE
Translation No --> Sv

### ISSUE THREAD

**Issue by Haxpett** [MVKVT16/WAKT#16]
Page interpreted as being in Norwegian and my phone asked me if I wanted a translation to Swedish.
![2016-10-03 09 34 31](https://cloud.githubusercontent.com/assets/8407258/19075825/e3ee46ec-8a46-11e6-9e16-2ed730f7f391.png)

**Comment by lokal-profil** [comment]
This is a problem with [Wikimedia-Sverige/ODOK](http://www.github.comWikimedia-Sverige/ODOK/issues) (not WAKT)
